Dev create post
Revature-Bubble/BackEnd pull request #2
Opened 2021-11-11 20:01 UTC by ajweaver13

Finished create post feature

2021-11-11 20:02 UTC, dawmckin approved these changes

2021-11-11 20:06 UTC, mxledesma approved these changes

2021-11-11 22:15 UTC, CJPete22 requested changes
- Make sure you have the .gitignore ignoring the .idea folder. 
- In the pom.xml please change DB_Password back to DB_PASS to keep the environment variables consistent.
- In the post controller please remove the (origins = "") as it will not always be from there
- You have a commented out method in the postservice. please remove it.
- Please remove all commented out methods. PostServiceImpl has one as well
- Please add full javadoc style comments to your controller and service layer classes
- Please complete the postRepo test class

2021-11-11 22:58 UTC, ajweaver13 commented
The get request for posts is not completely done. It does not implement individual gets and gets with followers.

2021-11-11 23:10 UTC, CJPete22 commented
The Post control has a merge notation left in it

2021-11-12 15:34 UTC, CJPete22 approved these changes

2021-11-12 15:35 UTC, merged